### ISSUE TITLE
efi

### ISSUE THREAD

**Issue by Hehande17** [viniciuscarrieri/hackintoshDellInspirion3583-#1]
hi  can you share share your efi？

**Comment by viniciuscarrieri** [comment]
You can download it is released.

**Comment by Hehande17** [comment]
OK thanks.

**Comment by Hehande17** [comment]
> You can download it is released.

👌，thanks.

**Comment by Hehande17** [comment]
hi，bro，my pc is inspire 5580 ，i have boot it by your efi in mac os. thanks.
